a = "guarav"
print(len(a))
print(a.upper())
print(a.lower())
print(a.rstrip())
print(a.capitalize())
print(len(a.center(50)))

print(a.count('gaurav'))
print(a.endswith('v'))
print(a.find('r'))
print(a.title)
print(a.isalnum())
print(a.isalpha())
print(a.islower())
print(a.isupper())
print(a.isprintable())
print(a.istitle())
print(a.swapcase())